services:
  - type: web
    name: undercover-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
