services:
  - type: web
    name: undercover-game-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
